// Generated by tools/make-icon.py; edit the scene there, then regenerate.
#ifndef APP_ICON_H
#define APP_ICON_H
#include <math.h>
#include <stddef.h>
#include <stdint.h>
typedef struct { int kind, count, minimum; float p[16], top[3], bottom[3]; } AppIconShape;
static const AppIconShape app_icon_shapes[] = {
    {0, 2, 0, {12,12,232,232,52,0,0,0,0,0,0,0,0,0,0,0}, {77,158,148}, {32,94,98}},
    {0, 2, 0, {14,14,228,228,50,0,0,0,0,0,0,0,0,0,0,0}, {77,158,148}, {32,94,98}},
    {0, 2, 0, {76,40,104,99,10,0,0,0,0,0,0,0,0,0,0,0}, {255,247,223}, {231,212,173}},
    {0, 2, 48, {92,60,72,6,3,0,0,0,0,0,0,0,0,0,0,0}, {131,134,111}, {131,134,111}},
    {0, 2, 48, {92,76,50,6,3,0,0,0,0,0,0,0,0,0,0,0}, {131,134,111}, {131,134,111}},
    {0, 2, 0, {47,99,162,19,9,0,0,0,0,0,0,0,0,0,0,0}, {21,61,65}, {21,61,65}},
    {1, 1, 0, {47,108,10,0,0,0,0,0,0,0,0,0,0,0,0,0}, {234,216,180}, {234,216,180}},
    {1, 1, 0, {209,108,10,0,0,0,0,0,0,0,0,0,0,0,0,0}, {234,216,180}, {234,216,180}},
    {0, 2, 0, {44,123,168,88,20,0,0,0,0,0,0,0,0,0,0,0}, {18,62,68}, {18,62,68}},
    {0, 2, 0, {44,115,168,84,20,0,0,0,0,0,0,0,0,0,0,0}, {255,242,212}, {222,188,137}},
    {0, 2, 0, {65,132,126,41,10,0,0,0,0,0,0,0,0,0,0,0}, {31,82,86}, {31,82,86}},
    {0, 2, 0, {76,140,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {100,140,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {124,140,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {148,140,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {172,140,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {76,156,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {100,156,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {124,156,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {148,156,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {172,156,12,7,3,0,0,0,0,0,0,0,0,0,0,0}, {247,228,188}, {247,228,188}},
    {0, 2, 0, {90,183,76,7,3.5,0,0,0,0,0,0,0,0,0,0,0}, {56,99,95}, {56,99,95}}
};
static float icon__clamp(float x, float a, float b) { return x<a?a:(x>b?b:x); }
static float icon__distance(const AppIconShape *s, float x, float y) {
    const float *p=s->p;
    if (s->kind==0) {
        float qx=fabsf(x-p[0]-p[2]/2)-(p[2]/2-p[4]);
        float qy=fabsf(y-p[1]-p[3]/2)-(p[3]/2-p[4]);
        return hypotf(fmaxf(qx,0),fmaxf(qy,0))+fminf(fmaxf(qx,qy),0)-p[4];
    }
    if (s->kind==1) return hypotf(x-p[0],y-p[1])-p[2];
    float nearest=1e9f;
    int inside=0;
    for (int i=0,j=s->count-1;i<s->count;j=i++) {
        float ax=p[2*j],ay=p[2*j+1],bx=p[2*i],by=p[2*i+1];
        float dx=bx-ax,dy=by-ay;
        float t=icon__clamp(((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy),0,1);
        nearest=fminf(nearest,hypotf(x-ax-t*dx,y-ay-t*dy));
        if (((ay>y)!=(by>y)) && x<(bx-ax)*(y-ay)/(by-ay)+ax) inside=!inside;
    }
    return inside?-nearest:nearest;
}
// Straight RGBA, analytic edge coverage; detail is reduced at small sizes.
static void icon_render_rgba(uint8_t *rgba, int size) {
    if (!rgba || size<=0) return;
    for (int y=0;y<size;y++) for (int x=0;x<size;x++) {
        float px=(x+0.5f)*256/size,py=(y+0.5f)*256/size;
        float color[3]={0,0,0},alpha=0;
        for (size_t i=0;i<sizeof(app_icon_shapes)/sizeof(app_icon_shapes[0]);i++) {
            const AppIconShape *s=&app_icon_shapes[i];
            if (size<s->minimum) continue;
            float a=icon__clamp(0.5f-icon__distance(s,px,py)*size/256,0,1);
            if (a<=0) continue;
            float lo=s->p[1],hi=lo+s->p[3];
            if (s->kind==1) { lo=s->p[1]-s->p[2]; hi=s->p[1]+s->p[2]; }
            if (s->kind==2) {
                hi=lo;
                for (int j=1;j<s->count;j++) { lo=fminf(lo,s->p[2*j+1]); hi=fmaxf(hi,s->p[2*j+1]); }
            }
            float t=icon__clamp((py-lo)/(hi-lo),0,1);
            for (int k=0;k<3;k++) color[k]=(s->top[k]+t*(s->bottom[k]-s->top[k]))*a+color[k]*(1-a);
            alpha=a+alpha*(1-a);
        }
        uint8_t *out=rgba+((size_t)y*size+x)*4;
        for (int k=0;k<3;k++) out[k]=alpha>0?(uint8_t)(icon__clamp(color[k]/alpha,0,255)+0.5f):0;
        out[3]=(uint8_t)(alpha*255+0.5f);
    }
}
#endif
