"""Rebuild this app's editable SVG, PNG/ICO assets and C runtime renderer.
Run: python tools/make-icon.py (requires Pillow and gcc/CC).
The scene below is the source of truth. No image files are needed at runtime.
"""
from pathlib import Path
import io, json, os, shutil, struct, subprocess, tempfile
from PIL import Image

APP = 'typewriter'
SCENE = [
    ['rect', [12, 12, 232, 232, 52], '#4D9E94', '#205E62', 0],
    ['rect', [14, 14, 228, 228, 50], '#4D9E94', '#205E62', 0],
    ['rect', [76, 40, 104, 99, 10], '#FFF7DF', '#E7D4AD', 0],
    ['rect', [92, 60, 72, 6, 3], '#83866F', '#83866F', 48],
    ['rect', [92, 76, 50, 6, 3], '#83866F', '#83866F', 48],
    ['rect', [47, 99, 162, 19, 9], '#153D41', '#153D41', 0],
    ['circle', [47, 108, 10], '#EAD8B4', '#EAD8B4', 0],
    ['circle', [209, 108, 10], '#EAD8B4', '#EAD8B4', 0],
    ['rect', [44, 123, 168, 88, 20], '#123E44', '#123E44', 0],
    ['rect', [44, 115, 168, 84, 20], '#FFF2D4', '#DEBC89', 0],
    ['rect', [65, 132, 126, 41, 10], '#1F5256', '#1F5256', 0],
    ['rect', [76, 140, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [100, 140, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [124, 140, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [148, 140, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [172, 140, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [76, 156, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [100, 156, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [124, 156, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [148, 156, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [172, 156, 12, 7, 3], '#F7E4BC', '#F7E4BC', 0],
    ['rect', [90, 183, 76, 7, 3.5], '#38635F', '#38635F', 0],
]
ROOT = Path(__file__).resolve().parents[1]
ASSET = ROOT / ('resources')
STEM = 'typewriter-icon'
HEADER = 'icon.h'
SIZES = (16, 24, 32, 48, 64, 128, 256)

def rgb(c):
    return tuple(int(c[i:i+2], 16) for i in (1,3,5))

def export_svg():
    parts = ['<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 256 256">', '<title>' + APP + ' application icon</title>', '<defs>']
    for i,(kind,p,c,d,minimum) in enumerate(SCENE):
        parts.append(f'<linearGradient id="g{i}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="{c}"/><stop offset="1" stop-color="{d}"/></linearGradient>')
    parts.append('</defs>')
    for i,(kind,p,c,d,minimum) in enumerate(SCENE):
        fill = f'fill="url(#g{i})"'
        if kind == 'rect':
            x,y,w,h,r = p
            parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}" {fill}/>')
        elif kind == 'circle':
            x,y,r = p
            parts.append(f'<circle cx="{x}" cy="{y}" r="{r}" {fill}/>')
        else:
            points = ' '.join(f'{p[j]},{p[j+1]}' for j in range(0,len(p),2))
            parts.append(f'<polygon points="{points}" {fill}/>')
    parts.append('</svg>')
    (ASSET / (STEM+'.svg')).write_text('\n'.join(parts)+'\n',encoding='utf8')

def renderer():
    shapes = []
    for kind,p,c,d,minimum in SCENE:
        coords = p + [0]*(16-len(p))
        shapes.append('    {%d, %d, %d, {%s}, {%s}, {%s}}' % (
            {'rect':0,'circle':1,'poly':2}[kind],len(p)//2,minimum,
            ','.join(str(v) for v in coords), ','.join(map(str,rgb(c))), ','.join(map(str,rgb(d)))))
    return r"""// Generated by tools/make-icon.py; edit the scene there, then regenerate.
#ifndef APP_ICON_H
#define APP_ICON_H
#include <math.h>
#include <stddef.h>
#include <stdint.h>
typedef struct { int kind, count, minimum; float p[16], top[3], bottom[3]; } AppIconShape;
static const AppIconShape app_icon_shapes[] = {
""" + ',\n'.join(shapes) + r"""
};
static float icon__clamp(float x, float a, float b) { return x<a?a:(x>b?b:x); }
static float icon__distance(const AppIconShape *s, float x, float y) {
    const float *p=s->p;
    if (s->kind==0) {
        float qx=fabsf(x-p[0]-p[2]/2)-(p[2]/2-p[4]);
        float qy=fabsf(y-p[1]-p[3]/2)-(p[3]/2-p[4]);
        return hypotf(fmaxf(qx,0),fmaxf(qy,0))+fminf(fmaxf(qx,qy),0)-p[4];
    }
    if (s->kind==1) return hypotf(x-p[0],y-p[1])-p[2];
    float nearest=1e9f;
    int inside=0;
    for (int i=0,j=s->count-1;i<s->count;j=i++) {
        float ax=p[2*j],ay=p[2*j+1],bx=p[2*i],by=p[2*i+1];
        float dx=bx-ax,dy=by-ay;
        float t=icon__clamp(((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy),0,1);
        nearest=fminf(nearest,hypotf(x-ax-t*dx,y-ay-t*dy));
        if (((ay>y)!=(by>y)) && x<(bx-ax)*(y-ay)/(by-ay)+ax) inside=!inside;
    }
    return inside?-nearest:nearest;
}
// Straight RGBA, analytic edge coverage; detail is reduced at small sizes.
static void icon_render_rgba(uint8_t *rgba, int size) {
    if (!rgba || size<=0) return;
    for (int y=0;y<size;y++) for (int x=0;x<size;x++) {
        float px=(x+0.5f)*256/size,py=(y+0.5f)*256/size;
        float color[3]={0,0,0},alpha=0;
        for (size_t i=0;i<sizeof(app_icon_shapes)/sizeof(app_icon_shapes[0]);i++) {
            const AppIconShape *s=&app_icon_shapes[i];
            if (size<s->minimum) continue;
            float a=icon__clamp(0.5f-icon__distance(s,px,py)*size/256,0,1);
            if (a<=0) continue;
            float lo=s->p[1],hi=lo+s->p[3];
            if (s->kind==1) { lo=s->p[1]-s->p[2]; hi=s->p[1]+s->p[2]; }
            if (s->kind==2) {
                hi=lo;
                for (int j=1;j<s->count;j++) { lo=fminf(lo,s->p[2*j+1]); hi=fmaxf(hi,s->p[2*j+1]); }
            }
            float t=icon__clamp((py-lo)/(hi-lo),0,1);
            for (int k=0;k<3;k++) color[k]=(s->top[k]+t*(s->bottom[k]-s->top[k]))*a+color[k]*(1-a);
            alpha=a+alpha*(1-a);
        }
        uint8_t *out=rgba+((size_t)y*size+x)*4;
        for (int k=0;k<3;k++) out[k]=alpha>0?(uint8_t)(icon__clamp(color[k]/alpha,0,255)+0.5f):0;
        out[3]=(uint8_t)(alpha*255+0.5f);
    }
}
#endif
"""

def main():
    ASSET.mkdir(parents=True, exist_ok=True)
    export_svg()
    header=renderer()
    if HEADER:
        (ROOT / HEADER).write_text(header,encoding='utf8')
    cc=os.environ.get('CC') or shutil.which('gcc') or shutil.which('cc')
    if not cc: raise SystemExit('Install gcc or set CC to a C compiler.')
    with tempfile.TemporaryDirectory(prefix='app-icon-') as folder:
        tmp=Path(folder)
        (tmp/'icon.h').write_text(header,encoding='utf8')
        (tmp/'render.c').write_text('#include "icon.h"\n#include <stdio.h>\n#include <stdlib.h>\nint main(int argc,char **argv) { if(argc!=3)return 1; int n=atoi(argv[1]); if(n<1 || n>1024)return 1; uint8_t *p=malloc((size_t)n*n*4); if(!p)return 1; icon_render_rgba(p,n); FILE *f=fopen(argv[2],"wb"); if(!f){free(p);return 1;} size_t count=fwrite(p,4,(size_t)n*n,f); int ok=fclose(f); free(p); return count==(size_t)n*n && ok==0?0:1; }',encoding='utf8')
        exe=tmp/('render.exe' if os.name=='nt' else 'render')
        subprocess.run([cc,'-O2','-std=c11',str(tmp/'render.c'),'-o',str(exe),'-lm'],check=True)
        frames=[]
        for size in sorted(set(SIZES+(512,1024))):
            raw=tmp/'pixels.rgba'
            subprocess.run([str(exe),str(size),str(raw)],check=True)
            im=Image.frombytes('RGBA',(size,size),raw.read_bytes())
            if APP=='typewriter' and size in (16,32,64,128,256,512,1024):
                im.save(ASSET/f'icon_{size}.png')
            if size==1024: im.save(ASSET/(STEM+'.png'))
            if size in SIZES:
                data=io.BytesIO(); im.save(data,format='PNG'); frames.append((size,data.getvalue()))
        offset=6+16*len(frames)
        directory=bytearray(struct.pack('<HHH',0,1,len(frames)))
        for size,data in frames:
            directory.extend(struct.pack('<BBBBHHII',size%256,size%256,0,0,1,32,len(data),offset))
            offset+=len(data)
        ico=ROOT/'icon.ico' if APP=='typewriter' else ASSET/(('atelier-icon' if APP=='Atelier' else APP.lower())+'.ico')
        ico.write_bytes(directory+b''.join(data for _,data in frames))
        print(f'{APP}: exported SVG, PNG, 7-size ICO'+(' and runtime renderer' if HEADER else ''))
if __name__=='__main__': main()
